sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  "8.11.3"
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - "curl -LO https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip"
    - "unzip chromedriver_linux64.zip"
    - "npm install"
before_script:
  - "npm start &"
script:
    - "npm test"
  